import type { ProviderConfig } from "./types.js";

export const PROVIDERS: Record<string, ProviderConfig> = {
  "302ai": { id: "302ai", name: "302.AI", kind: "openai", baseUrl: "https://api.302.ai/v1", env: ["302AI_API_KEY"] },
  "abacus": { id: "abacus", name: "Abacus", kind: "openai", baseUrl: "https://routellm.abacus.ai/v1", env: ["ABACUS_API_KEY"] },
  "abliteration-ai": { id: "abliteration-ai", name: "abliteration.ai", kind: "openai", baseUrl: "https://api.abliteration.ai/v1", env: ["ABLIT_KEY"] },
  "ai-router": { id: "ai-router", name: "AI-ROUTER", kind: "openai", baseUrl: "https://api.ai-router.dev/v1", env: ["AI_ROUTER_API_KEY"] },
  "aiand": { id: "aiand", name: "ai&", kind: "openai", baseUrl: "https://api.aiand.com/v1", env: ["AIAND_API_KEY"] },
  "aihubmix": { id: "aihubmix", name: "AIHubMix", kind: "openai", baseUrl: "https://api.aihubmix.com/v1", env: ["AIHUBMIX_API_KEY"] },
  "aki-io": { id: "aki-io", name: "AKI.IO", kind: "openai", baseUrl: "https://aki.io/v1", env: ["AKI_IO_API_KEY"] },
  "alibaba": { id: "alibaba", name: "Alibaba", kind: "openai", baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", env: ["DASHSCOPE_API_KEY"] },
  "alibaba-cn": { id: "alibaba-cn", name: "Alibaba (China)", kind: "openai", baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", env: ["DASHSCOPE_API_KEY"] },
  "alibaba-coding-plan": { id: "alibaba-coding-plan", name: "Alibaba Coding Plan", kind: "openai", baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1", env: ["ALIBABA_CODING_PLAN_API_KEY"] },
  "alibaba-coding-plan-cn": { id: "alibaba-coding-plan-cn", name: "Alibaba Coding Plan (China)", kind: "openai", baseUrl: "https://coding.dashscope.aliyuncs.com/v1", env: ["ALIBABA_CODING_PLAN_API_KEY"] },
  "alibaba-token-plan": { id: "alibaba-token-plan", name: "Alibaba Token Plan", kind: "openai", baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1", env: ["ALIBABA_TOKEN_PLAN_API_KEY"] },
  "alibaba-token-plan-cn": { id: "alibaba-token-plan-cn", name: "Alibaba Token Plan (China)", kind: "openai", baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1", env: ["ALIBABA_TOKEN_PLAN_API_KEY"] },
  "amazon-bedrock": { id: "amazon-bedrock", name: "Amazon Bedrock", kind: "sdk", env: ["AWS_ACCESS_KEY_ID","AWS_SECRET_ACCESS_KEY","AWS_REGION","AWS_BEARER_TOKEN_BEDROCK"], note: "requires AWS SDK credential chain (SigV4), not OpenAI-compatible" },
  "ambient": { id: "ambient", name: "Ambient", kind: "openai", baseUrl: "https://api.ambient.xyz/v1", env: ["AMBIENT_API_KEY"] },
  "anthropic": { id: "anthropic", name: "Anthropic", kind: "anthropic", baseUrl: "https://api.anthropic.com", env: ["ANTHROPIC_API_KEY"] },
  "anyapi": { id: "anyapi", name: "AnyAPI", kind: "openai", baseUrl: "https://api.anyapi.ai/v1", env: ["ANYAPI_API_KEY"] },
  "atomic-chat": { id: "atomic-chat", name: "Atomic Chat", kind: "openai", baseUrl: "http://127.0.0.1:1337/v1", env: ["ATOMIC_CHAT_API_KEY"] },
  "auriko": { id: "auriko", name: "Auriko", kind: "openai", baseUrl: "https://api.auriko.ai/v1", env: ["AURIKO_API_KEY"] },
  "azure": { id: "azure", name: "Azure", kind: "azure", env: ["AZURE_RESOURCE_NAME","AZURE_API_KEY"], note: "needs AZURE_RESOURCE_NAME" },
  "azure-cognitive-services": { id: "azure-cognitive-services", name: "Azure Cognitive Services", kind: "azure", env: ["AZURE_COGNITIVE_SERVICES_RESOURCE_NAME","AZURE_COGNITIVE_SERVICES_API_KEY"], note: "needs AZURE_COGNITIVE_SERVICES_RESOURCE_NAME" },
  "bailing": { id: "bailing", name: "Bailing", kind: "openai", baseUrl: "https://api.tbox.cn/api/llm/v1/chat/completions", env: ["BAILING_API_TOKEN"] },
  "baseten": { id: "baseten", name: "Baseten", kind: "openai", baseUrl: "https://inference.baseten.co/v1", env: ["BASETEN_API_KEY"] },
  "berget": { id: "berget", name: "Berget.AI", kind: "openai", baseUrl: "https://api.berget.ai/v1", env: ["BERGET_API_KEY"] },
  "blueclaw": { id: "blueclaw", name: "Blue Claw", kind: "openai", baseUrl: "https://openai.blueclaw.network/v1", env: ["BLUECLAW_API_KEY"] },
  "cerebras": { id: "cerebras", name: "Cerebras", kind: "openai", baseUrl: "https://api.cerebras.ai/v1", env: ["CEREBRAS_API_KEY"], headers: {"X-Cerebras-3rd-Party-Integration":"algorithme"} },
  "chutes": { id: "chutes", name: "Chutes", kind: "openai", baseUrl: "https://llm.chutes.ai/v1", env: ["CHUTES_API_KEY"] },
  "clarifai": { id: "clarifai", name: "Clarifai", kind: "openai", baseUrl: "https://api.clarifai.com/v2/ext/openai/v1", env: ["CLARIFAI_PAT"] },
  "claudinio": { id: "claudinio", name: "Claudinio", kind: "openai", baseUrl: "https://api.claudin.io/v1", env: ["CLAUDINIO_API_KEY"] },
  "cline-pass": { id: "cline-pass", name: "ClinePass", kind: "openai", baseUrl: "https://api.cline.bot/api/v1", env: ["CLINE_API_KEY"] },
  "cloudferro-sherlock": { id: "cloudferro-sherlock", name: "CloudFerro Sherlock", kind: "openai", baseUrl: "https://api-sherlock.cloudferro.com/openai/v1/", env: ["CLOUDFERRO_SHERLOCK_API_KEY"] },
  "cloudflare-ai-gateway": { id: "cloudflare-ai-gateway", name: "Cloudflare AI Gateway", kind: "sdk", env: ["CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID","CLOUDFLARE_GATEWAY_ID"], note: "requires Cloudflare AI Gateway provider SDK" },
  "cloudflare-workers-ai": { id: "cloudflare-workers-ai", name: "Cloudflare Workers AI", kind: "openai", baseUrl: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1", env: ["CLOUDFLARE_API_KEY","CLOUDFLARE_ACCOUNT_ID"] },
  "cohere": { id: "cohere", name: "Cohere", kind: "openai", baseUrl: "https://api.cohere.ai/compatibility/v1", env: ["COHERE_API_KEY"] },
  "cortecs": { id: "cortecs", name: "Cortecs", kind: "openai", baseUrl: "https://api.cortecs.ai/v1", env: ["CORTECS_API_KEY"] },
  "crof": { id: "crof", name: "CrofAI", kind: "openai", baseUrl: "https://crof.ai/v1", env: ["CROF_API_KEY"] },
  "crossmodel": { id: "crossmodel", name: "CrossModel", kind: "openai", baseUrl: "https://api.crossmodel.ai/v1", env: ["CROSSMODEL_API_KEY"] },
  "daoxe": { id: "daoxe", name: "DaoXE", kind: "openai", baseUrl: "https://daoxe.com/v1", env: ["DAOXE_API_KEY"] },
  "databricks": { id: "databricks", name: "Databricks", kind: "openai", baseUrl: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1", env: ["DATABRICKS_HOST","DATABRICKS_TOKEN"] },
  "deepinfra": { id: "deepinfra", name: "Deep Infra", kind: "openai", baseUrl: "https://api.deepinfra.com/v1/openai", env: ["DEEPINFRA_API_KEY"] },
  "deepseek": { id: "deepseek", name: "DeepSeek", kind: "openai", baseUrl: "https://api.deepseek.com", env: ["DEEPSEEK_API_KEY"] },
  "digitalocean": { id: "digitalocean", name: "DigitalOcean", kind: "openai", baseUrl: "https://inference.do-ai.run/v1", env: ["DIGITALOCEAN_ACCESS_TOKEN"] },
  "dinference": { id: "dinference", name: "DInference", kind: "openai", baseUrl: "https://api.dinference.com/v1", env: ["DINFERENCE_API_KEY"] },
  "drun": { id: "drun", name: "D.Run (China)", kind: "openai", baseUrl: "https://chat.d.run/v1", env: ["DRUN_API_KEY"] },
  "ebcloud": { id: "ebcloud", name: "EBCloud", kind: "openai", baseUrl: "https://maas-api.ebcloud.com/v1", env: ["EBCLOUD_API_KEY"] },
  "empiriolabs": { id: "empiriolabs", name: "EmpirioLabs AI", kind: "openai", baseUrl: "https://api.empiriolabs.ai/v1", env: ["EMPIRIOLABS_API_KEY"] },
  "evroc": { id: "evroc", name: "evroc", kind: "openai", baseUrl: "https://models.think.evroc.com/v1", env: ["EVROC_API_KEY"] },
  "fastrouter": { id: "fastrouter", name: "FastRouter", kind: "openai", baseUrl: "https://go.fastrouter.ai/api/v1", env: ["FASTROUTER_API_KEY"] },
  "fireworks-ai": { id: "fireworks-ai", name: "Fireworks AI", kind: "openai", baseUrl: "https://api.fireworks.ai/inference/v1/", env: ["FIREWORKS_API_KEY"] },
  "freemodel": { id: "freemodel", name: "FreeModel", kind: "anthropic", baseUrl: "https://cc.freemodel.dev/v1", env: ["FREEMODEL_API_KEY"] },
  "friendli": { id: "friendli", name: "Friendli", kind: "openai", baseUrl: "https://api.friendli.ai/serverless/v1", env: ["FRIENDLI_TOKEN"] },
  "frogbot": { id: "frogbot", name: "FrogBot", kind: "openai", baseUrl: "https://app.frogbot.ai/api/v1", env: ["FROGBOT_API_KEY"] },
  "github-copilot": { id: "github-copilot", name: "GitHub Copilot", kind: "openai", baseUrl: "https://api.githubcopilot.com", env: ["GITHUB_TOKEN"] },
  "gitlab": { id: "gitlab", name: "GitLab Duo", kind: "sdk", env: ["GITLAB_TOKEN"], note: "requires gitlab-ai-provider SDK (Duo) auth" },
  "gmicloud": { id: "gmicloud", name: "GMI Cloud", kind: "openai", baseUrl: "https://api.gmi-serving.com/v1", env: ["GMICLOUD_API_KEY"] },
  "google": { id: "google", name: "Google", kind: "gemini", baseUrl: "https://generativelanguage.googleapis.com/v1beta", env: ["GOOGLE_API_KEY","GOOGLE_GENERATIVE_AI_API_KEY","GEMINI_API_KEY"] },
  "google-vertex": { id: "google-vertex", name: "Vertex", kind: "sdk", env: ["GOOGLE_VERTEX_PROJECT","GOOGLE_VERTEX_LOCATION","GOOGLE_APPLICATION_CREDENTIALS"], note: "requires GCP ADC / service account, not OpenAI-compatible" },
  "google-vertex-anthropic": { id: "google-vertex-anthropic", name: "Vertex (Anthropic)", kind: "sdk", env: ["GOOGLE_VERTEX_PROJECT","GOOGLE_VERTEX_LOCATION","GOOGLE_APPLICATION_CREDENTIALS"], note: "requires GCP ADC / service account, not OpenAI-compatible" },
  "greenpt": { id: "greenpt", name: "GreenPT", kind: "openai", baseUrl: "https://api.greenpt.ai/v1", env: ["GREENPT_API_KEY"] },
  "groq": { id: "groq", name: "Groq", kind: "openai", baseUrl: "https://api.groq.com/openai/v1", env: ["GROQ_API_KEY"] },
  "helicone": { id: "helicone", name: "Helicone", kind: "openai", baseUrl: "https://ai-gateway.helicone.ai/v1", env: ["HELICONE_API_KEY"] },
  "hetzner": { id: "hetzner", name: "Hetzner", kind: "openai", baseUrl: "https://inference.hetzner.com/api/v1", env: ["HETZNER_API_KEY"] },
  "hpc-ai": { id: "hpc-ai", name: "HPC-AI", kind: "openai", baseUrl: "https://api.hpc-ai.com/inference/v1", env: ["HPC_AI_API_KEY"] },
  "huggingface": { id: "huggingface", name: "Hugging Face", kind: "openai", baseUrl: "https://router.huggingface.co/v1", env: ["HF_TOKEN"] },
  "hyper": { id: "hyper", name: "Charm Hyper", kind: "openai", baseUrl: "https://hyper.charm.land/v1", env: ["HYPER_API_KEY"] },
  "iflowcn": { id: "iflowcn", name: "iFlow", kind: "openai", baseUrl: "https://apis.iflow.cn/v1", env: ["IFLOW_API_KEY"] },
  "impossibl": { id: "impossibl", name: "Impossibl", kind: "openai", baseUrl: "https://api.impossibl.com/v1", env: ["IMPOSSIBL_API_KEY"] },
  "inception": { id: "inception", name: "Inception", kind: "openai", baseUrl: "https://api.inceptionlabs.ai/v1/", env: ["INCEPTION_API_KEY"] },
  "inceptron": { id: "inceptron", name: "Inceptron", kind: "openai", baseUrl: "https://api.inceptron.io/v1", env: ["INCEPTRON_API_KEY"] },
  "inference": { id: "inference", name: "Inference", kind: "openai", baseUrl: "https://inference.net/v1", env: ["INFERENCE_API_KEY"] },
  "inferx": { id: "inferx", name: "InferX", kind: "openai", baseUrl: "https://model.inferx.net/endpoints/v1", env: ["INFERX_API_KEY"] },
  "infomaniak": { id: "infomaniak", name: "Infomaniak", kind: "openai", baseUrl: "https://api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1", env: ["INFOMANIAK_API_KEY","INFOMANIAK_PRODUCT_ID"] },
  "io-net": { id: "io-net", name: "IO.NET", kind: "openai", baseUrl: "https://api.intelligence.io.solutions/api/v1", env: ["IOINTELLIGENCE_API_KEY"] },
  "jiekou": { id: "jiekou", name: "Jiekou.AI", kind: "openai", baseUrl: "https://api.jiekou.ai/openai", env: ["JIEKOU_API_KEY"] },
  "kenari": { id: "kenari", name: "Kenari", kind: "openai", baseUrl: "https://kenari.id/v1", env: ["KENARI_API_KEY"] },
  "kilo": { id: "kilo", name: "Kilo Gateway", kind: "openai", baseUrl: "https://api.kilo.ai/api/gateway", env: ["KILO_API_KEY"], headers: {"HTTP-Referer":"https://opencode.ai/","X-Title":"algorithme"} },
  "kimi-for-coding": { id: "kimi-for-coding", name: "Kimi For Coding", kind: "anthropic", baseUrl: "https://api.kimi.com/coding/v1", env: ["KIMI_API_KEY"] },
  "kuae-cloud-coding-plan": { id: "kuae-cloud-coding-plan", name: "KUAE Cloud Coding Plan", kind: "openai", baseUrl: "https://coding-plan-endpoint.kuaecloud.net/v1", env: ["KUAE_API_KEY"] },
  "lilac": { id: "lilac", name: "Lilac", kind: "openai", baseUrl: "https://api.getlilac.com/v1", env: ["LILAC_API_KEY"] },
  "llama": { id: "llama", name: "Llama", kind: "openai", baseUrl: "https://api.llama.com/compat/v1/", env: ["LLAMA_API_KEY"] },
  "llmgateway": { id: "llmgateway", name: "LLM Gateway", kind: "openai", baseUrl: "https://api.llmgateway.io/v1", env: ["LLMGATEWAY_API_KEY"], headers: {"HTTP-Referer":"https://opencode.ai/","X-Title":"algorithme","X-Source":"opencode"} },
  "llmtr": { id: "llmtr", name: "LLMTR", kind: "openai", baseUrl: "https://llmtr.com/v1", env: ["LLMTR_API_KEY"] },
  "lmstudio": { id: "lmstudio", name: "LMStudio", kind: "openai", baseUrl: "http://127.0.0.1:1234/v1", env: ["LMSTUDIO_API_KEY"], includeUsage: false },
  "longcat": { id: "longcat", name: "LongCat", kind: "openai", baseUrl: "https://api.longcat.chat/openai", env: ["LONGCAT_API_KEY"] },
  "lucidquery": { id: "lucidquery", name: "LucidQuery", kind: "openai", baseUrl: "https://api.lucidquery.com/v1", env: ["LUCIDQUERY_API_KEY"] },
  "lynkr": { id: "lynkr", name: "Lynkr", kind: "openai", baseUrl: "http://127.0.0.1:8081/v1", env: ["LYNKR_API_KEY"] },
  "meganova": { id: "meganova", name: "Meganova", kind: "openai", baseUrl: "https://api.meganova.ai/v1", env: ["MEGANOVA_API_KEY"] },
  "merge-gateway": { id: "merge-gateway", name: "Merge Gateway", kind: "sdk", env: ["MERGE_GATEWAY_API_KEY"], note: "requires merge-gateway-ai-sdk-provider" },
  "meta": { id: "meta", name: "Meta", kind: "openai", baseUrl: "https://api.meta.ai/v1", env: ["META_MODEL_API_KEY"] },
  "minimax": { id: "minimax", name: "MiniMax (minimax.io)", kind: "anthropic", baseUrl: "https://api.minimax.io/anthropic/v1", env: ["MINIMAX_API_KEY"] },
  "minimax-cn": { id: "minimax-cn", name: "MiniMax (minimaxi.com)", kind: "anthropic", baseUrl: "https://api.minimaxi.com/anthropic/v1", env: ["MINIMAX_API_KEY"] },
  "minimax-cn-coding-plan": { id: "minimax-cn-coding-plan", name: "MiniMax Token Plan (minimaxi.com)", kind: "anthropic", baseUrl: "https://api.minimaxi.com/anthropic/v1", env: ["MINIMAX_API_KEY"] },
  "minimax-coding-plan": { id: "minimax-coding-plan", name: "MiniMax Token Plan (minimax.io)", kind: "anthropic", baseUrl: "https://api.minimax.io/anthropic/v1", env: ["MINIMAX_API_KEY"] },
  "mistral": { id: "mistral", name: "Mistral", kind: "openai", baseUrl: "https://api.mistral.ai/v1", env: ["MISTRAL_API_KEY"] },
  "mixlayer": { id: "mixlayer", name: "Mixlayer", kind: "openai", baseUrl: "https://models.mixlayer.ai/v1", env: ["MIXLAYER_API_KEY"] },
  "moark": { id: "moark", name: "Moark", kind: "openai", baseUrl: "https://moark.com/v1", env: ["MOARK_API_KEY"] },
  "modal": { id: "modal", name: "Modal", kind: "openai", baseUrl: "https://inference.us-west.modal.direct/v1", env: ["MODAL_PROXY_TOKEN"] },
  "model-oracle-ai": { id: "model-oracle-ai", name: "Model Oracle AI", kind: "openai", baseUrl: "https://api.modeloracle.com/api/v1", env: ["MODEL_ORACLE_API_KEY"] },
  "modelis": { id: "modelis", name: "Modelis", kind: "openai", baseUrl: "https://modelishub.com/v1", env: ["MODELIS_API_KEY"] },
  "modelscope": { id: "modelscope", name: "ModelScope", kind: "openai", baseUrl: "https://api-inference.modelscope.cn/v1", env: ["MODELSCOPE_API_KEY"] },
  "moonshotai": { id: "moonshotai", name: "Moonshot AI", kind: "openai", baseUrl: "https://api.moonshot.ai/v1", env: ["MOONSHOT_API_KEY"] },
  "moonshotai-cn": { id: "moonshotai-cn", name: "Moonshot AI (China)", kind: "openai", baseUrl: "https://api.moonshot.cn/v1", env: ["MOONSHOT_API_KEY"] },
  "morph": { id: "morph", name: "Morph", kind: "openai", baseUrl: "https://api.morphllm.com/v1", env: ["MORPH_API_KEY"] },
  "nano-gpt": { id: "nano-gpt", name: "NanoGPT", kind: "openai", baseUrl: "https://nano-gpt.com/api/v1", env: ["NANO_GPT_API_KEY"] },
  "nearai": { id: "nearai", name: "NEAR AI Cloud", kind: "openai", baseUrl: "https://cloud-api.near.ai/v1", env: ["NEARAI_API_KEY"] },
  "nebius": { id: "nebius", name: "Nebius Token Factory", kind: "openai", baseUrl: "https://api.tokenfactory.nebius.com/v1", env: ["NEBIUS_API_KEY"] },
  "neon": { id: "neon", name: "Neon", kind: "openai", baseUrl: "${NEON_AI_GATEWAY_BASE_URL}/v1", env: ["NEON_AI_GATEWAY_BASE_URL","NEON_AI_GATEWAY_TOKEN"] },
  "neuralwatt": { id: "neuralwatt", name: "Neuralwatt", kind: "openai", baseUrl: "https://api.neuralwatt.com/v1", env: ["NEURALWATT_API_KEY"] },
  "nova": { id: "nova", name: "Nova", kind: "openai", baseUrl: "https://api.nova.amazon.com/v1", env: ["NOVA_API_KEY"] },
  "novita-ai": { id: "novita-ai", name: "NovitaAI", kind: "openai", baseUrl: "https://api.novita.ai/openai", env: ["NOVITA_API_KEY"] },
  "nvidia": { id: "nvidia", name: "Nvidia", kind: "openai", baseUrl: "https://integrate.api.nvidia.com/v1", env: ["NVIDIA_API_KEY"], headers: {"HTTP-Referer":"https://opencode.ai/","X-Title":"algorithme","X-BILLING-INVOKE-ORIGIN":"OpenCode"} },
  "ofox": { id: "ofox", name: "Ofox", kind: "openai", baseUrl: "https://api.ofox.ai/v1", env: ["OFOX_API_KEY"] },
  "ollama-cloud": { id: "ollama-cloud", name: "Ollama Cloud", kind: "openai", baseUrl: "https://ollama.com/v1", env: ["OLLAMA_API_KEY"] },
  "openai": { id: "openai", name: "OpenAI", kind: "openai", baseUrl: "https://api.openai.com/v1", env: ["OPENAI_API_KEY"] },
  "opencode": { id: "opencode", name: "OpenCode Zen", kind: "openai", baseUrl: "https://opencode.ai/zen/v1", env: ["OPENCODE_API_KEY"] },
  "opencode-go": { id: "opencode-go", name: "OpenCode Go", kind: "openai", baseUrl: "https://opencode.ai/zen/go/v1", env: ["OPENCODE_API_KEY"] },
  "openrouter": { id: "openrouter", name: "OpenRouter", kind: "openai", baseUrl: "https://openrouter.ai/api/v1", env: ["OPENROUTER_API_KEY"], headers: {"HTTP-Referer":"https://github.com/zakmijo2-dotcom/Algorithmes-agent","X-Title":"Algorithme AI Agent"} },
  "orcarouter": { id: "orcarouter", name: "OrcaRouter", kind: "openai", baseUrl: "https://api.orcarouter.ai/v1", env: ["ORCAROUTER_API_KEY"] },
  "ovhcloud": { id: "ovhcloud", name: "OVHcloud AI Endpoints", kind: "openai", baseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1", env: ["OVHCLOUD_API_KEY"] },
  "perplexity": { id: "perplexity", name: "Perplexity", kind: "openai", baseUrl: "https://api.perplexity.ai", env: ["PERPLEXITY_API_KEY"] },
  "perplexity-agent": { id: "perplexity-agent", name: "Perplexity Agent", kind: "openai", baseUrl: "https://api.perplexity.ai/v1", env: ["PERPLEXITY_API_KEY"] },
  "pioneer": { id: "pioneer", name: "Pioneer", kind: "openai", baseUrl: "https://api.pioneer.ai/v1", env: ["PIONEER_API_KEY"] },
  "poe": { id: "poe", name: "Poe", kind: "openai", baseUrl: "https://api.poe.com/v1", env: ["POE_API_KEY"] },
  "poolside": { id: "poolside", name: "Poolside", kind: "openai", baseUrl: "https://inference.poolside.ai/v1", env: ["POOLSIDE_API_KEY"] },
  "privatemode-ai": { id: "privatemode-ai", name: "Privatemode AI", kind: "openai", baseUrl: "http://localhost:8080/v1", env: ["PRIVATEMODE_API_KEY","PRIVATEMODE_ENDPOINT"] },
  "qihang-ai": { id: "qihang-ai", name: "QiHang", kind: "openai", baseUrl: "https://api.qhaigc.net/v1", env: ["QIHANG_API_KEY"] },
  "qiniu-ai": { id: "qiniu-ai", name: "Qiniu", kind: "openai", baseUrl: "https://api.qnaigc.com/v1", env: ["QINIU_API_KEY"] },
  "qvac": { id: "qvac", name: "QVAC", kind: "sdk", env: ["QVAC_API_KEY"], note: "requires @qvac/ai-sdk-provider" },
  "regolo-ai": { id: "regolo-ai", name: "Regolo AI", kind: "openai", baseUrl: "https://api.regolo.ai/v1", env: ["REGOLO_API_KEY"] },
  "requesty": { id: "requesty", name: "Requesty", kind: "openai", baseUrl: "https://router.requesty.ai/v1", env: ["REQUESTY_API_KEY"] },
  "routing-run": { id: "routing-run", name: "routing.run", kind: "openai", baseUrl: "https://api.routing.run/v1", env: ["ROUTING_RUN_API_KEY"] },
  "sakana": { id: "sakana", name: "Sakana AI", kind: "openai", baseUrl: "https://api.sakana.ai/v1", env: ["SAKANA_API_KEY"] },
  "salad-cloud": { id: "salad-cloud", name: "SaladCloud AI Gateway", kind: "sdk", env: ["SALAD_CLOUD_API_KEY"], note: "requires @saladtechnologies-oss/ai-sdk-provider" },
  "sap-ai-core": { id: "sap-ai-core", name: "SAP AI Core", kind: "sdk", env: ["AICORE_SERVICE_KEY"], note: "requires SAP AI Core service key parsing, not OpenAI-compatible" },
  "sarvam": { id: "sarvam", name: "Sarvam AI", kind: "openai", baseUrl: "https://api.sarvam.ai/v1", env: ["SARVAM_API_KEY"] },
  "scaleway": { id: "scaleway", name: "Scaleway", kind: "openai", baseUrl: "https://api.scaleway.ai/v1", env: ["SCALEWAY_API_KEY"] },
  "scx": { id: "scx", name: "SCX.ai", kind: "openai", baseUrl: "https://api.scx.ai/v1", env: ["SCX_API_KEY"] },
  "siliconflow": { id: "siliconflow", name: "SiliconFlow", kind: "openai", baseUrl: "https://api.siliconflow.com/v1", env: ["SILICONFLOW_API_KEY"] },
  "siliconflow-cn": { id: "siliconflow-cn", name: "SiliconFlow (China)", kind: "openai", baseUrl: "https://api.siliconflow.cn/v1", env: ["SILICONFLOW_CN_API_KEY"] },
  "snowflake-cortex": { id: "snowflake-cortex", name: "Snowflake Cortex", kind: "openai", baseUrl: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1", env: ["SNOWFLAKE_ACCOUNT","SNOWFLAKE_CORTEX_PAT"] },
  "stackit": { id: "stackit", name: "STACKIT", kind: "openai", baseUrl: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1", env: ["STACKIT_API_KEY"] },
  "stepfun": { id: "stepfun", name: "StepFun (China)", kind: "openai", baseUrl: "https://api.stepfun.com/v1", env: ["STEPFUN_API_KEY"] },
  "stepfun-ai": { id: "stepfun-ai", name: "StepFun (Global)", kind: "openai", baseUrl: "https://api.stepfun.ai/v1", env: ["STEPFUN_API_KEY"] },
  "stepfun-ai-step-plan": { id: "stepfun-ai-step-plan", name: "StepFun Step Plan (Global)", kind: "openai", baseUrl: "https://api.stepfun.ai/step_plan/v1", env: ["STEPFUN_API_KEY"] },
  "stepfun-step-plan": { id: "stepfun-step-plan", name: "StepFun Step Plan (China)", kind: "openai", baseUrl: "https://api.stepfun.com/step_plan/v1", env: ["STEPFUN_API_KEY"] },
  "subconscious": { id: "subconscious", name: "Subconscious", kind: "anthropic", baseUrl: "https://api.subconscious.dev/v1", env: ["SUBCONSCIOUS_API_KEY"] },
  "submodel": { id: "submodel", name: "submodel", kind: "openai", baseUrl: "https://llm.submodel.ai/v1", env: ["SUBMODEL_INSTAGEN_ACCESS_KEY"] },
  "synthetic": { id: "synthetic", name: "Synthetic", kind: "openai", baseUrl: "https://api.synthetic.new/openai/v1", env: ["SYNTHETIC_API_KEY"] },
  "tencent-coding-plan": { id: "tencent-coding-plan", name: "Tencent Coding Plan (China)", kind: "openai", baseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3", env: ["TENCENT_CODING_PLAN_API_KEY"] },
  "tencent-token-plan": { id: "tencent-token-plan", name: "Tencent Token Plan", kind: "openai", baseUrl: "https://api.lkeap.cloud.tencent.com/plan/v3", env: ["TENCENT_TOKEN_PLAN_API_KEY"] },
  "tencent-tokenhub": { id: "tencent-tokenhub", name: "Tencent TokenHub", kind: "openai", baseUrl: "https://tokenhub.tencentmaas.com/v1", env: ["TENCENT_TOKENHUB_API_KEY"] },
  "tensorx": { id: "tensorx", name: "TensorX", kind: "openai", baseUrl: "https://api.tensorx.ai/v1", env: ["TENSORX_API_KEY"] },
  "the-grid-ai": { id: "the-grid-ai", name: "The Grid AI", kind: "openai", baseUrl: "https://api.thegrid.ai/v1", env: ["THEGRID_API_KEY"] },
  "thinkingmachines": { id: "thinkingmachines", name: "Thinking Machines", kind: "anthropic", baseUrl: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1", env: ["TINKER_API_KEY"] },
  "tinfoil": { id: "tinfoil", name: "Tinfoil", kind: "openai", baseUrl: "https://inference.tinfoil.sh/v1", env: ["TINFOIL_API_KEY"] },
  "togetherai": { id: "togetherai", name: "Together AI", kind: "openai", baseUrl: "https://api.together.xyz/v1", env: ["TOGETHER_API_KEY"] },
  "trustedrouter": { id: "trustedrouter", name: "TrustedRouter", kind: "openai", baseUrl: "https://api.trustedrouter.com/v1", env: ["TRUSTEDROUTER_API_KEY"] },
  "umans-ai": { id: "umans-ai", name: "Umans AI", kind: "openai", baseUrl: "https://api.code.umans.ai/v1", env: ["UMANS_AI_API_KEY"] },
  "umans-ai-coding-plan": { id: "umans-ai-coding-plan", name: "Umans AI Coding Plan", kind: "openai", baseUrl: "https://api.code.umans.ai/v1", env: ["UMANS_AI_CODING_PLAN_API_KEY"] },
  "unorouter": { id: "unorouter", name: "UnoRouter", kind: "openai", baseUrl: "https://api.unorouter.com/v1", env: ["UNOROUTER_API_KEY"] },
  "upstage": { id: "upstage", name: "Upstage", kind: "openai", baseUrl: "https://api.upstage.ai/v1/solar", env: ["UPSTAGE_API_KEY"] },
  "v0": { id: "v0", name: "v0", kind: "openai", baseUrl: "https://api.gateway.vercel.ai/v1", env: ["V0_API_KEY"] },
  "venice": { id: "venice", name: "Venice AI", kind: "openai", baseUrl: "https://api.venice.ai/api/v1", env: ["VENICE_API_KEY"] },
  "vercel": { id: "vercel", name: "Vercel AI Gateway", kind: "openai", baseUrl: "https://api.gateway.vercel.ai/v1", env: ["V0_API_KEY"], headers: {"http-referer":"https://opencode.ai/","x-title":"algorithme"} },
  "vivgrid": { id: "vivgrid", name: "Vivgrid", kind: "openai", baseUrl: "https://api.vivgrid.com/v1", env: ["VIVGRID_API_KEY"] },
  "vultr": { id: "vultr", name: "Vultr", kind: "openai", baseUrl: "https://api.vultrinference.com/v1", env: ["VULTR_API_KEY"] },
  "wafer.ai": { id: "wafer.ai", name: "Wafer", kind: "openai", baseUrl: "https://pass.wafer.ai/v1", env: ["WAFER_API_KEY"] },
  "wandb": { id: "wandb", name: "Weights & Biases", kind: "openai", baseUrl: "https://api.inference.wandb.ai/v1", env: ["WANDB_API_KEY"] },
  "watsonx": { id: "watsonx", name: "watsonx.ai", kind: "sdk", env: ["WATSONX_AI_APIKEY","WATSONX_AI_PROJECT_ID"], note: "requires watsonx-ai-provider SDK auth" },
  "xai": { id: "xai", name: "xAI", kind: "openai", baseUrl: "https://api.x.ai/v1", env: ["XAI_API_KEY"] },
  "xiaomi": { id: "xiaomi", name: "Xiaomi", kind: "openai", baseUrl: "https://api.xiaomimimo.com/v1", env: ["XIAOMI_API_KEY"] },
  "xiaomi-token-plan-ams": { id: "xiaomi-token-plan-ams", name: "Xiaomi Token Plan (Europe)", kind: "openai", baseUrl: "https://token-plan-ams.xiaomimimo.com/v1", env: ["XIAOMI_API_KEY"] },
  "xiaomi-token-plan-cn": { id: "xiaomi-token-plan-cn", name: "Xiaomi Token Plan (China)", kind: "openai", baseUrl: "https://token-plan-cn.xiaomimimo.com/v1", env: ["XIAOMI_API_KEY"] },
  "xiaomi-token-plan-sgp": { id: "xiaomi-token-plan-sgp", name: "Xiaomi Token Plan (Singapore)", kind: "openai", baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1", env: ["XIAOMI_API_KEY"] },
  "xpersona": { id: "xpersona", name: "Xpersona", kind: "openai", baseUrl: "https://www.xpersona.co/v1", env: ["XPERSONA_API_KEY"] },
  "zai": { id: "zai", name: "Z.AI", kind: "openai", baseUrl: "https://api.z.ai/api/paas/v4", env: ["ZHIPU_API_KEY"] },
  "zai-coding-plan": { id: "zai-coding-plan", name: "Z.AI Coding Plan", kind: "openai", baseUrl: "https://api.z.ai/api/coding/paas/v4", env: ["ZHIPU_API_KEY"] },
  "zeldoc": { id: "zeldoc", name: "Zeldoc", kind: "openai", baseUrl: "https://api.zeldoc.ai/v1", env: ["ZELDOC_API_KEY"] },
  "zenifra": { id: "zenifra", name: "Zenifra", kind: "openai", baseUrl: "https://ai.zenifra.com/v1", env: ["ZENIFRA_AI_KEY"] },
  "zenmux": { id: "zenmux", name: "ZenMux", kind: "openai", baseUrl: "https://zenmux.ai/api/v1", env: ["ZENMUX_API_KEY"], headers: {"HTTP-Referer":"https://opencode.ai/","X-Title":"algorithme"} },
  "zhipuai": { id: "zhipuai", name: "Zhipu AI", kind: "openai", baseUrl: "https://open.bigmodel.cn/api/paas/v4", env: ["ZHIPU_API_KEY"] },
  "zhipuai-coding-plan": { id: "zhipuai-coding-plan", name: "Zhipu AI Coding Plan", kind: "openai", baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4", env: ["ZHIPU_API_KEY"] },
};